# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# based on example at https://github.com/hadley/tibble/blob/master/.travis.yml
# Explanation of .Rbuildignore and other things:  http://jtleek.com/protocols/travis_bioc_devel/
# Details for 'language: r' specification:  https://docs.travis-ci.com/user/languages/r/
# Online check for syntax of .travis.yml (but doesn't work for R format):  http://lint.travis-ci.org/

#language: c
#
#before_install:
#  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
#  - chmod 755 ./travis-tool.sh
#  - ./travis-tool.sh bootstrap
#install:
#  - ./travis-tool.sh install_deps
#script: ./travis-tool.sh run_tests
#
#after_failure:
#  - ./travis-tool.sh dump_logs
#
#notifications:
#  email:
#    on_success: change
#    on_failure: change
#

language: r
cache: packages

r_packages:
  - utils
  - stats
  - testthat
  - mapproj
  - maptools
  - deldir
  - PBSmapping
  - RANN
  - colorspace
  - RandomFields
  - shape
  - devtools
  - mixtools
  - sp
  - maps
  - mapdata
  - TMB

cache: packages

sudo: required

dist: trusty

addons:
  postgresql: "9.6"

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - # install postgis from source:
  - sudo apt-get --yes install libjson-c-dev postgresql-server-dev-9.6
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)
  - # activate liblwgeom:
  - sudo ldconfig
  - # create postgis databases:
  - sudo service postgresql restart
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - createdb empty
  - psql -d empty -c "CREATE EXTENSION postgis;"

warnings_are_errors: true

after_success:
  - dropdb postgis
  - createdb postgis
  - psql -d postgis -c "CREATE EXTENSION postgis;"
  - psql -d postgis -c "GRANT CREATE ON DATABASE postgis TO travis"
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - kaskr/TMB_contrib_R/TMBhelper

warnings_are_errors: false

notifications:
  email:
    on_success: change
    on_failure: change
